<?php declare(strict_types = 1);
//
// Generated by Smalldb\StateMachine\CodeGenerator\InferClass\SmalldbEntityGenerator (@InferSmalldbEntity annotation).
// Do NOT edit! All changes will be lost!
// 
// 
namespace Smalldb\StateMachine\Test\Example\SupervisorProcess\SupervisorProcessData;

use DateTimeImmutable;
use Smalldb\StateMachine\CodeGenerator\Annotation\InferredClass;
use Smalldb\StateMachine\Test\Example\SupervisorProcess\SupervisorProcessData;
use Smalldb\StateMachine\Test\Example\SupervisorProcess\SupervisorProcessData\SupervisorProcessDataImmutableInterface;


/**
 * @InferredClass
 */
class SupervisorProcessDataImmutable extends SupervisorProcessData implements SupervisorProcessDataImmutableInterface
{

	public function getId(): int
	{
		return $this->id;
	}


	public function getState(): string
	{
		return $this->state;
	}


	public function getCommand(): string
	{
		return $this->command;
	}


	public function getCreatedAt(): DateTimeImmutable
	{
		return $this->createdAt;
	}


	public function getModifiedAt(): DateTimeImmutable
	{
		return $this->modifiedAt;
	}


	public function getMemoryLimit(): ?int
	{
		return $this->memoryLimit;
	}


	public function getArgs(): ?array
	{
		return $this->args;
	}

}

