<?php declare(strict_types = 1);
/*
 * Copyright (c) 2017-2019, Josef Kufner  <josef@kufner.cz>
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

namespace Smalldb\StateMachine\Utils;


/**
 * Write PHP files in a convenient way.
 */
class PhpFileWriter
{
	private $indent = "";
	private $indentDepth = 0;

	private $buffer = '';

	private $headerComment = null;
	private $fileNamespace = null;
	private $generatorName = null;

	/** @var string[] */
	private $useAliases = [];
	/** @var int[] */
	private $usedAliasesCounter = [];


	/**
	 * PhpFileWriter constructor.
	 */
	public function __construct()
	{
	}


	public function write(string $filename)
	{
		file_put_contents($filename, $this->getPhpCode());
	}

	public function getPhpCode(): string
	{
		$code = "<?php declare(strict_types = 1);\n";
		$code .= $this->headerComment;
		$code .= "\n";

		if ($this->fileNamespace) {
			$code .= "namespace " . $this->fileNamespace . ";\n\n";
		}
		foreach ($this->useAliases as $className => $alias) {
			if ($this->getShortClassName($className) === $alias) {
				$code .= "use $className;\n";
			} else {
				$code .= "use $className as $alias;\n";
			}
		}

		$code .= "\n";
		$code .= $this->buffer;
		$code .= "\n";
		return $code;
	}


	public static function toCamelCase(string $identifier): string
	{
		return str_replace('_', '', ucwords($identifier, '_'));
	}


	public static function getShortClassName(string $fqcn): string
	{
		$lastSlashPos = strrpos($fqcn, '\\');
		return $lastSlashPos === false ? $fqcn : substr($fqcn, $lastSlashPos + 1);
	}


	public static function getClassNamespace(string $fqcn): string
	{
		$lastSlashPos = strrpos($fqcn, '\\');
		return $lastSlashPos === false ? '' : substr($fqcn, $fqcn[0] == '/' ? 1 : 0, $lastSlashPos);
	}


	public function useClass(string $fqcn): string
	{
		if (isset($this->useAliases[$fqcn])) {
			return $this->useAliases[$fqcn];
		} else {
			$alias = $this->getShortClassName($fqcn);
			if (isset($this->usedAliasesCounter[$alias])) {
				$alias .= '_' . ($this->usedAliasesCounter[$alias]++);
			} else if (preg_match('/_[0-9]+$/', $alias)) {
				$this->usedAliasesCounter[$alias] = 1;
				$alias .= '_0';
			} else {
				$this->usedAliasesCounter[$alias] = 1;
			}
			$this->useAliases[$fqcn] = $alias;
			return $alias;
		}
	}


	public function writeln(string $string = '', ...$args): self
	{
		if ($string !== '') {
			$this->buffer .= $this->indent;
			if (count($args) > 0) {
				$this->buffer .= vsprintf($string, array_map(function($v) { return var_export($v, true); }, $args));
			} else {
				$this->buffer .= $string;
			}
		}
		$this->buffer .= "\n";
		return $this;
	}


	public function close(): self
	{
		if ($this->indentDepth !== 0) {
			throw new \RuntimeException("Block not closed when generating PHP file.");
		}
		return $this;
	}


	public function setFileHeader(string $generator_class_name): self
	{
		$this->headerComment = "//" . str_replace("\n", "\n// ", "\n"
			. "Generated by $generator_class_name class.\n"
			. ""
			. "Do NOT edit! All changes will be lost!\n"
			. "\n");
		return $this;
	}


	public function beginBlock(string $statement = ''): self
	{
		if ($statement === '') {
			$this->writeln("{");
		} else {
			$this->writeln("$statement {");
		}
		$this->indent = $this->indent."\t";
		$this->indentDepth++;
		return $this;
	}

	public function endBlock(): self
	{
		$this->indentDepth--;
		$this->indent = str_repeat("\t", $this->indentDepth);
		$this->writeln("}");
		return $this;
	}

	public function comment(string $comment): self
	{
		$this->writeln("// ".str_replace("\n", "\n// ", $comment));
		return $this;
	}


	public function setNamespace(string $namespace): self
	{
		$this->fileNamespace = $namespace;
		return $this;
	}


	public function beginClass(string $classname, ?string $extends = null, array $implements = []): self
	{
		$this->writeln("class $classname"
			. ($extends ? " extends " . $extends : '')
			. ($implements  ? " implements " . join(', ', $implements) : ''));
		$this->beginBlock();
		return $this;
	}


	public function beginAbstractClass(string $classname): self
	{
		$this->writeln("abstract class $classname");
		$this->beginBlock();
		return $this;
	}


	public function endClass(): self
	{
		$this->endBlock();
		return $this;
	}


	public function beginMethod(string $name, array $args = [], $returnType = ''): self
	{
		$this->writeln('');
		$this->writeln("public function $name(".join(', ', $args).")".($returnType === '' ? '' : ": $returnType"));
		$this->beginBlock();
		return $this;
	}

	public function beginFinalMethod(string $name, array $args = [], $returnType = ''): self
	{
		$this->writeln('');
		$this->writeln("public final function $name(".join(', ', $args).")".($returnType === '' ? '' : ": $returnType"));
		$this->beginBlock();
		return $this;
	}


	public function endMethod(): self
	{
		$this->endBlock();
		$this->writeln('');
		return $this;
	}

}
