<?php declare(strict_types = 1);
//
// Generated by Smalldb\StateMachine\CodeGenerator\DtoGenerator.
// Do NOT edit! All changes will be lost!
// 
// 
namespace Smalldb\StateMachine\Test\Example\Post\PostData;

use DateTimeImmutable;
use Smalldb\StateMachine\CodeCooker\Annotation\GeneratedClass;


/**
 * @GeneratedClass
 * @see \Smalldb\StateMachine\Test\Example\Post\PostProperties
 */
interface PostData
{

	public function getId(): ?int;

	public function getTitle(): string;

	public function getSlug(): string;

	public function getSummary(): string;

	public function getContent(): string;

	public function getPublishedAt(): DateTimeImmutable;

	public function getAuthorId(): int;

	public function getCommentCount(): ?int;
}

