<?php declare(strict_types = 1);
//
// Generated by Smalldb\CodeCooker\Generator\DtoGenerator.
// Do NOT edit! All changes will be lost!
// 
// 
namespace Smalldb\StateMachine\Test\Example\Comment\CommentData;

use DateTimeImmutable;
use Smalldb\CodeCooker\Annotation\GeneratedClass;


/**
 * @GeneratedClass
 * @see \Smalldb\StateMachine\Test\Example\Comment\CommentProperties
 */
interface CommentData
{

	public function getId(): ?int;

	public function getPostId(): int;

	public function getContent(): string;

	public function getPublishedAt(): DateTimeImmutable;

	public function getAuthorId(): int;

	public function isLegitComment(): bool;
}

